-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [guide_check]: function definitions
import Aeneas
import GuideCheck.Code.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace guide_check

/-- [guide_check::bytes_equal]: loop body 0:
    Source: 'crates/guide-check/src/lib.rs', lines 48:4-55:1
    Visibility: public -/
@[rust_loop_body]
def bytes_equal_loop.body
  (a : Slice Std.U8) (b : Slice Std.U8) (i : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i1 := Slice.len a
  if i < i1
  then
    let i2 ← Slice.index_usize a i
    let i3 ← Slice.index_usize b i
    if i2 != i3
    then ok (done false)
    else let i4 ← i + 1#usize
         ok (cont i4)
  else ok (done true)

/-- [guide_check::bytes_equal]: loop 0:
    Source: 'crates/guide-check/src/lib.rs', lines 48:4-55:1
    Visibility: public -/
@[rust_loop]
def bytes_equal_loop
  (a : Slice Std.U8) (b : Slice Std.U8) (i : Std.Usize) : Result Bool := do
  loop
    (fun i1 => bytes_equal_loop.body a b i1)
    i

/-- [guide_check::bytes_equal]:
    Source: 'crates/guide-check/src/lib.rs', lines 43:0-55:1
    Visibility: public -/
def bytes_equal (a : Slice Std.U8) (b : Slice Std.U8) : Result Bool := do
  let i := Slice.len a
  let i1 := Slice.len b
  if i != i1
  then ok false
  else bytes_equal_loop a b 0#usize

/-- [guide_check::next_kept]: loop body 0:
    Source: 'crates/guide-check/src/lib.rs', lines 60:4-67:1
    Visibility: public -/
@[rust_loop_body]
def next_kept_loop.body
  (mask : Slice Bool) (j : Std.Usize) :
  Result (ControlFlow Std.Usize Std.Usize)
  := do
  let i := Slice.len mask
  if j < i
  then
    let b ← Slice.index_usize mask j
    if b
    then let j1 ← j + 1#usize
         ok (cont j1)
    else ok (done j)
  else ok (done j)

/-- [guide_check::next_kept]: loop 0:
    Source: 'crates/guide-check/src/lib.rs', lines 60:4-67:1
    Visibility: public -/
@[rust_loop]
def next_kept_loop (mask : Slice Bool) (j : Std.Usize) : Result Std.Usize := do
  loop
    (fun j1 => next_kept_loop.body mask j1)
    j

/-- [guide_check::next_kept]:
    Source: 'crates/guide-check/src/lib.rs', lines 58:0-67:1
    Visibility: public -/
@[reducible]
def next_kept (mask : Slice Bool) (i : Std.Usize) : Result Std.Usize := do
  next_kept_loop mask i

/-- [guide_check::lines_left]:
    Source: 'crates/guide-check/src/lib.rs', lines 70:0-75:1
    Visibility: public -/
def lines_left
  (i : Std.Usize) (n : Std.Usize) (j : Std.Usize) (m : Std.Usize) :
  Result Bool
  := do
  if i < n
  then ok true
  else ok (j < m)

/-- [guide_check::kept_equal_from]: loop body 0:
    Source: 'crates/guide-check/src/lib.rs', lines 1:0-105:1
    Visibility: public -/
@[rust_loop_body]
def kept_equal_from_loop.body
  (old : Slice (alloc.vec.Vec Std.U8)) (removed : Slice Bool)
  (new : Slice (alloc.vec.Vec Std.U8)) (added : Slice Bool) (i : Std.Usize)
  (j : Std.Usize) :
  Result (ControlFlow (Std.Usize × Std.Usize) Bool)
  := do
  let i1 := Slice.len old
  let i2 := Slice.len new
  let b ← lines_left i i1 j i2
  if b
  then
    let a ← next_kept removed i
    let b1 ← next_kept added j
    let i3 := Slice.len old
    if a >= i3
    then let i4 := Slice.len new
         ok (done (b1 >= i4))
    else
      let i4 := Slice.len new
      if b1 >= i4
      then ok (done false)
      else
        let v ← Slice.index_usize old a
        let s := alloc.vec.Vec.deref v
        let v1 ← Slice.index_usize new b1
        let s1 := alloc.vec.Vec.deref v1
        let b2 ← bytes_equal s s1
        if b2
        then let i5 ← a + 1#usize
             let j1 ← b1 + 1#usize
             ok (cont (i5, j1))
        else ok (done false)
  else ok (done true)

/-- [guide_check::kept_equal_from]: loop 0:
    Source: 'crates/guide-check/src/lib.rs', lines 1:0-105:1
    Visibility: public -/
@[rust_loop]
def kept_equal_from_loop
  (old : Slice (alloc.vec.Vec Std.U8)) (removed : Slice Bool)
  (new : Slice (alloc.vec.Vec Std.U8)) (added : Slice Bool) (i : Std.Usize)
  (j : Std.Usize) :
  Result Bool
  := do
  loop
    (fun (i1, j1) => kept_equal_from_loop.body old removed new added i1 j1)
    (i, j)

/-- [guide_check::kept_equal_from]:
    Source: 'crates/guide-check/src/lib.rs', lines 79:0-105:1
    Visibility: public -/
@[reducible]
def kept_equal_from
  (old : Slice (alloc.vec.Vec Std.U8)) (removed : Slice Bool)
  (new : Slice (alloc.vec.Vec Std.U8)) (added : Slice Bool) (i0 : Std.Usize)
  (j0 : Std.Usize) :
  Result Bool
  := do
  kept_equal_from_loop old removed new added i0 j0

/-- [guide_check::span_holds]:
    Source: 'crates/guide-check/src/lib.rs', lines 108:0-119:1
    Visibility: public -/
def span_holds
  (s : Span) (file : Std.Usize) (old : Bool) (line : Std.Usize) :
  Result Bool
  := do
  if s.file != file
  then ok false
  else
    if s.old != old
    then ok false
    else if line < s.from
         then ok false
         else ok (line <= s.to)

/-- [guide_check::covered]: loop body 0:
    Source: 'crates/guide-check/src/lib.rs', lines 124:4-131:1
    Visibility: public -/
@[rust_loop_body]
def covered_loop.body
  (spans : Slice Span) (file : Std.Usize) (old : Bool) (line : Std.Usize)
  (i : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i1 := Slice.len spans
  if i < i1
  then
    let s ← Slice.index_usize spans i
    let b ← span_holds s file old line
    if b
    then ok (done true)
    else let i2 ← i + 1#usize
         ok (cont i2)
  else ok (done false)

/-- [guide_check::covered]: loop 0:
    Source: 'crates/guide-check/src/lib.rs', lines 124:4-131:1
    Visibility: public -/
@[rust_loop]
def covered_loop
  (spans : Slice Span) (file : Std.Usize) (old : Bool) (line : Std.Usize)
  (i : Std.Usize) :
  Result Bool
  := do
  loop
    (fun i1 => covered_loop.body spans file old line i1)
    i

/-- [guide_check::covered]:
    Source: 'crates/guide-check/src/lib.rs', lines 122:0-131:1
    Visibility: public -/
@[reducible]
def covered
  (spans : Slice Span) (file : Std.Usize) (old : Bool) (line : Std.Usize) :
  Result Bool
  := do
  covered_loop spans file old line 0#usize

/-- [guide_check::mask_covered]: loop body 0:
    Source: 'crates/guide-check/src/lib.rs', lines 136:4-145:1
    Visibility: public -/
@[rust_loop_body]
def mask_covered_loop.body
  (spans : Slice Span) (file : Std.Usize) (old : Bool) (mask : Slice Bool)
  (k : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i := Slice.len mask
  if k < i
  then
    let b ← Slice.index_usize mask k
    if b
    then
      let i1 ← k + 1#usize
      let b1 ← covered spans file old i1
      if b1
      then ok (cont i1)
      else ok (done false)
    else let k1 ← k + 1#usize
         ok (cont k1)
  else ok (done true)

/-- [guide_check::mask_covered]: loop 0:
    Source: 'crates/guide-check/src/lib.rs', lines 136:4-145:1
    Visibility: public -/
@[rust_loop]
def mask_covered_loop
  (spans : Slice Span) (file : Std.Usize) (old : Bool) (mask : Slice Bool)
  (k : Std.Usize) :
  Result Bool
  := do
  loop
    (fun k1 => mask_covered_loop.body spans file old mask k1)
    k

/-- [guide_check::mask_covered]:
    Source: 'crates/guide-check/src/lib.rs', lines 134:0-145:1
    Visibility: public -/
@[reducible]
def mask_covered
  (spans : Slice Span) (file : Std.Usize) (old : Bool) (mask : Slice Bool) :
  Result Bool
  := do
  mask_covered_loop spans file old mask 0#usize

/-- [guide_check::file_ok]:
    Source: 'crates/guide-check/src/lib.rs', lines 148:0-162:1
    Visibility: public -/
def file_ok
  (d : FileDiff) (f : Std.Usize) (spans : Slice Span) : Result Bool := do
  let i := alloc.vec.Vec.len d.removed
  let i1 := alloc.vec.Vec.len d.old
  if i != i1
  then ok false
  else
    let i2 := alloc.vec.Vec.len d.added
    let i3 := alloc.vec.Vec.len d.new
    if i2 != i3
    then ok false
    else
      let s := alloc.vec.Vec.deref d.old
      let s1 := alloc.vec.Vec.deref d.removed
      let s2 := alloc.vec.Vec.deref d.new
      let s3 := alloc.vec.Vec.deref d.added
      let b ← kept_equal_from s s1 s2 s3 0#usize 0#usize
      if b
      then
        let s4 := alloc.vec.Vec.deref d.removed
        let b1 ← mask_covered spans f true s4
        if b1
        then
          let s5 := alloc.vec.Vec.deref d.added
          mask_covered spans f false s5
        else ok false
      else ok false

/-- [guide_check::files_ok]: loop body 0:
    Source: 'crates/guide-check/src/lib.rs', lines 167:4-174:1
    Visibility: public -/
@[rust_loop_body]
def files_ok_loop.body
  (files : Slice FileDiff) (spans : Slice Span) (f : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i := Slice.len files
  if f < i
  then
    let fd ← Slice.index_usize files f
    let b ← file_ok fd f spans
    if b
    then let f1 ← f + 1#usize
         ok (cont f1)
    else ok (done false)
  else ok (done true)

/-- [guide_check::files_ok]: loop 0:
    Source: 'crates/guide-check/src/lib.rs', lines 167:4-174:1
    Visibility: public -/
@[rust_loop]
def files_ok_loop
  (files : Slice FileDiff) (spans : Slice Span) (f : Std.Usize) :
  Result Bool
  := do
  loop
    (fun f1 => files_ok_loop.body files spans f1)
    f

/-- [guide_check::files_ok]:
    Source: 'crates/guide-check/src/lib.rs', lines 165:0-174:1
    Visibility: public -/
@[reducible]
def files_ok (files : Slice FileDiff) (spans : Slice Span) : Result Bool := do
  files_ok_loop files spans 0#usize

/-- [guide_check::has_change]: loop body 0:
    Source: 'crates/guide-check/src/lib.rs', lines 180:4-187:1
    Visibility: public -/
@[rust_loop_body]
def has_change_loop.body
  (mask : Slice Bool) («to» : Std.Usize) (k : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  if k < «to»
  then
    let b ← Slice.index_usize mask k
    if b
    then ok (done true)
    else let k1 ← k + 1#usize
         ok (cont k1)
  else ok (done false)

/-- [guide_check::has_change]: loop 0:
    Source: 'crates/guide-check/src/lib.rs', lines 180:4-187:1
    Visibility: public -/
@[rust_loop]
def has_change_loop
  (mask : Slice Bool) («to» : Std.Usize) (k : Std.Usize) : Result Bool := do
  loop
    (fun k1 => has_change_loop.body mask «to» k1)
    k

/-- [guide_check::has_change]:
    Source: 'crates/guide-check/src/lib.rs', lines 178:0-187:1
    Visibility: public -/
def has_change
  (mask : Slice Bool) («from» : Std.Usize) («to» : Std.Usize) :
  Result Bool
  := do
  let k ← «from» - 1#usize
  has_change_loop mask «to» k

/-- [guide_check::dist]:
    Source: 'crates/guide-check/src/lib.rs', lines 189:0-194:1
    Visibility: public -/
def dist (a : Std.Usize) (b : Std.Usize) : Result Std.Usize := do
  if a < b
  then b - a
  else a - b

/-- [guide_check::near]: loop body 0:
    Source: 'crates/guide-check/src/lib.rs', lines 199:4-208:1
    Visibility: public -/
@[rust_loop_body]
def near_loop.body
  (mask : Slice Bool) (line : Std.Usize) (pad : Std.Usize) (k : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i := Slice.len mask
  if k < i
  then
    let b ← Slice.index_usize mask k
    if b
    then
      let i1 ← k + 1#usize
      let i2 ← dist i1 line
      if i2 <= pad
      then ok (done true)
      else ok (cont i1)
    else let k1 ← k + 1#usize
         ok (cont k1)
  else ok (done false)

/-- [guide_check::near]: loop 0:
    Source: 'crates/guide-check/src/lib.rs', lines 199:4-208:1
    Visibility: public -/
@[rust_loop]
def near_loop
  (mask : Slice Bool) (line : Std.Usize) (pad : Std.Usize) (k : Std.Usize) :
  Result Bool
  := do
  loop
    (fun k1 => near_loop.body mask line pad k1)
    k

/-- [guide_check::near]:
    Source: 'crates/guide-check/src/lib.rs', lines 197:0-208:1
    Visibility: public -/
@[reducible]
def near
  (mask : Slice Bool) (line : Std.Usize) (pad : Std.Usize) : Result Bool := do
  near_loop mask line pad 0#usize

/-- [guide_check::all_near]: loop body 0:
    Source: 'crates/guide-check/src/lib.rs', lines 213:4-220:1
    Visibility: public -/
@[rust_loop_body]
def all_near_loop.body
  (mask : Slice Bool) («to» : Std.Usize) (pad : Std.Usize) (k : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  if k < «to»
  then
    let i ← k + 1#usize
    let b ← near mask i pad
    if b
    then ok (cont i)
    else ok (done false)
  else ok (done true)

/-- [guide_check::all_near]: loop 0:
    Source: 'crates/guide-check/src/lib.rs', lines 213:4-220:1
    Visibility: public -/
@[rust_loop]
def all_near_loop
  (mask : Slice Bool) («to» : Std.Usize) (pad : Std.Usize) (k : Std.Usize) :
  Result Bool
  := do
  loop
    (fun k1 => all_near_loop.body mask «to» pad k1)
    k

/-- [guide_check::all_near]:
    Source: 'crates/guide-check/src/lib.rs', lines 211:0-220:1
    Visibility: public -/
def all_near
  (mask : Slice Bool) («from» : Std.Usize) («to» : Std.Usize)
  (pad : Std.Usize) :
  Result Bool
  := do
  let k ← «from» - 1#usize
  all_near_loop mask «to» pad k

/-- [guide_check::span_fits]:
    Source: 'crates/guide-check/src/lib.rs', lines 223:0-237:1
    Visibility: public -/
def span_fits
  (mask : Slice Bool) («from» : Std.Usize) («to» : Std.Usize)
  (pad : Std.Usize) :
  Result Bool
  := do
  if «from» = 0#usize
  then ok false
  else
    if «from» > «to»
    then ok false
    else
      let i := Slice.len mask
      if «to» > i
      then ok false
      else
        let b ← has_change mask «from» «to»
        if b
        then all_near mask «from» «to» pad
        else ok false

/-- [guide_check::span_ok]:
    Source: 'crates/guide-check/src/lib.rs', lines 239:0-247:1
    Visibility: public -/
def span_ok
  (s : Span) (files : Slice FileDiff) (pad : Std.Usize) : Result Bool := do
  let i := Slice.len files
  if s.file >= i
  then ok false
  else
    if s.old
    then
      let fd ← Slice.index_usize files s.file
      let s1 := alloc.vec.Vec.deref fd.removed
      span_fits s1 s.from s.to pad
    else
      let fd ← Slice.index_usize files s.file
      let s1 := alloc.vec.Vec.deref fd.added
      span_fits s1 s.from s.to pad

/-- [guide_check::spans_ok]: loop body 0:
    Source: 'crates/guide-check/src/lib.rs', lines 251:4-258:1
    Visibility: public -/
@[rust_loop_body]
def spans_ok_loop.body
  (spans : Slice Span) (files : Slice FileDiff) (pad : Std.Usize)
  (i : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i1 := Slice.len spans
  if i < i1
  then
    let s ← Slice.index_usize spans i
    let b ← span_ok s files pad
    if b
    then let i2 ← i + 1#usize
         ok (cont i2)
    else ok (done false)
  else ok (done true)

/-- [guide_check::spans_ok]: loop 0:
    Source: 'crates/guide-check/src/lib.rs', lines 251:4-258:1
    Visibility: public -/
@[rust_loop]
def spans_ok_loop
  (spans : Slice Span) (files : Slice FileDiff) (pad : Std.Usize)
  (i : Std.Usize) :
  Result Bool
  := do
  loop
    (fun i1 => spans_ok_loop.body spans files pad i1)
    i

/-- [guide_check::spans_ok]:
    Source: 'crates/guide-check/src/lib.rs', lines 249:0-258:1
    Visibility: public -/
@[reducible]
def spans_ok
  (spans : Slice Span) (files : Slice FileDiff) (pad : Std.Usize) :
  Result Bool
  := do
  spans_ok_loop spans files pad 0#usize

/-- [guide_check::check]:
    Source: 'crates/guide-check/src/lib.rs', lines 261:0-266:1
    Visibility: public -/
def check
  (files : Slice FileDiff) (spans : Slice Span) (pad : Std.Usize) :
  Result Bool
  := do
  let b ← files_ok files spans
  if b
  then spans_ok spans files pad
  else ok false

/-- [guide_check::{impl core::clone::Clone for guide_check::Kind}::clone]:
    Source: 'crates/guide-check/src/lib.rs', lines 269:9-269:14
    Visibility: public -/
def Kind.Insts.CoreCloneClone.clone (self : Kind) : Result Kind := do
  ok self

/-- Trait implementation: [guide_check::{impl core::clone::Clone for guide_check::Kind}]
    Source: 'crates/guide-check/src/lib.rs', lines 269:9-269:14 -/
@[reducible]
def Kind.Insts.CoreCloneClone : core.clone.Clone Kind := {
  clone := Kind.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [guide_check::{impl core::marker::Copy for guide_check::Kind}]
    Source: 'crates/guide-check/src/lib.rs', lines 269:16-269:20 -/
@[reducible]
def Kind.Insts.CoreMarkerCopy : core.marker.Copy Kind := {
  cloneInst := Kind.Insts.CoreCloneClone
}

/-- [guide_check::{impl core::fmt::Debug for guide_check::Kind}::fmt]:
    Source: 'crates/guide-check/src/lib.rs', lines 269:22-269:27
    Visibility: public -/
def Kind.Insts.CoreFmtDebug.fmt
  (self : Kind) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | Kind.Same => core.fmt.Formatter.write_str f (toStr "Same")
  | Kind.Removed => core.fmt.Formatter.write_str f (toStr "Removed")
  | Kind.Added => core.fmt.Formatter.write_str f (toStr "Added")
  | Kind.Header => core.fmt.Formatter.write_str f (toStr "Header")

/-- Trait implementation: [guide_check::{impl core::fmt::Debug for guide_check::Kind}]
    Source: 'crates/guide-check/src/lib.rs', lines 269:22-269:27 -/
@[reducible]
def Kind.Insts.CoreFmtDebug : core.fmt.Debug Kind := {
  fmt := Kind.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [guide_check::{impl core::marker::StructuralPartialEq for guide_check::Kind}]
    Source: 'crates/guide-check/src/lib.rs', lines 269:29-269:38 -/
@[reducible]
def Kind.Insts.CoreMarkerStructuralPartialEq : core.marker.StructuralPartialEq
  Kind := {
}

/-- [guide_check::{impl core::cmp::PartialEq<guide_check::Kind> for guide_check::Kind}::eq]:
    Source: 'crates/guide-check/src/lib.rs', lines 269:29-269:38
    Visibility: public -/
def Kind.Insts.CoreCmpPartialEqKind.eq
  (self : Kind) (other : Kind) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [guide_check::{impl core::cmp::PartialEq<guide_check::Kind> for guide_check::Kind}]
    Source: 'crates/guide-check/src/lib.rs', lines 269:29-269:38 -/
@[reducible]
def Kind.Insts.CoreCmpPartialEqKind : core.cmp.PartialEq Kind Kind := {
  eq := Kind.Insts.CoreCmpPartialEqKind.eq
}

/-- [guide_check::{impl core::cmp::Eq for guide_check::Kind}::assert_fields_are_eq]:
    Source: 'crates/guide-check/src/lib.rs', lines 269:40-269:42
    Visibility: public -/
def Kind.Insts.CoreCmpEq.assert_fields_are_eq (self : Kind) : Result Unit := do
  ok ()

/-- Trait implementation: [guide_check::{impl core::cmp::Eq for guide_check::Kind}]
    Source: 'crates/guide-check/src/lib.rs', lines 269:40-269:42 -/
@[reducible]
def Kind.Insts.CoreCmpEq : core.cmp.Eq Kind := {
  partialEqInst := Kind.Insts.CoreCmpPartialEqKind
  assert_fields_are_eq := Kind.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [guide_check::{impl core::clone::Clone for guide_check::Row}::clone]:
    Source: 'crates/guide-check/src/lib.rs', lines 283:9-283:14
    Visibility: public -/
def Row.Insts.CoreCloneClone.clone (self : Row) : Result Row := do
  ok self

/-- Trait implementation: [guide_check::{impl core::clone::Clone for guide_check::Row}]
    Source: 'crates/guide-check/src/lib.rs', lines 283:9-283:14 -/
@[reducible]
def Row.Insts.CoreCloneClone : core.clone.Clone Row := {
  clone := Row.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [guide_check::{impl core::marker::Copy for guide_check::Row}]
    Source: 'crates/guide-check/src/lib.rs', lines 283:16-283:20 -/
@[reducible]
def Row.Insts.CoreMarkerCopy : core.marker.Copy Row := {
  cloneInst := Row.Insts.CoreCloneClone
}

/-- [guide_check::{impl core::fmt::Debug for guide_check::Row}::fmt]:
    Source: 'crates/guide-check/src/lib.rs', lines 283:22-283:27
    Visibility: public -/
def Row.Insts.CoreFmtDebug.fmt
  (self : Row) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ Kind.Insts.CoreFmtDebug self.kind
  let dyn1 := Dyn.mk _ core.fmt.DebugUsize self.old
  let dyn2 := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugUsize) self.new
  core.fmt.Formatter.debug_struct_field3_finish f (toStr "Row") (toStr "kind")
    dyn (toStr "old") dyn1 (toStr "new") dyn2

/-- Trait implementation: [guide_check::{impl core::fmt::Debug for guide_check::Row}]
    Source: 'crates/guide-check/src/lib.rs', lines 283:22-283:27 -/
@[reducible]
def Row.Insts.CoreFmtDebug : core.fmt.Debug Row := {
  fmt := Row.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [guide_check::{impl core::marker::StructuralPartialEq for guide_check::Row}]
    Source: 'crates/guide-check/src/lib.rs', lines 283:29-283:38 -/
@[reducible]
def Row.Insts.CoreMarkerStructuralPartialEq : core.marker.StructuralPartialEq
  Row := {
}

/-- [guide_check::{impl core::cmp::PartialEq<guide_check::Row> for guide_check::Row}::eq]:
    Source: 'crates/guide-check/src/lib.rs', lines 283:29-283:38
    Visibility: public -/
def Row.Insts.CoreCmpPartialEqRow.eq
  (self : Row) (other : Row) : Result Bool := do
  let b ← Kind.Insts.CoreCmpPartialEqKind.eq self.kind other.kind
  if b
  then if self.old = other.old
       then ok (self.new = other.new)
       else ok false
  else ok false

/-- Trait implementation: [guide_check::{impl core::cmp::PartialEq<guide_check::Row> for guide_check::Row}]
    Source: 'crates/guide-check/src/lib.rs', lines 283:29-283:38 -/
@[reducible]
def Row.Insts.CoreCmpPartialEqRow : core.cmp.PartialEq Row Row := {
  eq := Row.Insts.CoreCmpPartialEqRow.eq
}

/-- [guide_check::{impl core::cmp::Eq for guide_check::Row}::assert_fields_are_eq]:
    Source: 'crates/guide-check/src/lib.rs', lines 283:40-283:42
    Visibility: public -/
def Row.Insts.CoreCmpEq.assert_fields_are_eq (self : Row) : Result Unit := do
  ok ()

/-- Trait implementation: [guide_check::{impl core::cmp::Eq for guide_check::Row}]
    Source: 'crates/guide-check/src/lib.rs', lines 283:40-283:42 -/
@[reducible]
def Row.Insts.CoreCmpEq : core.cmp.Eq Row := {
  partialEqInst := Row.Insts.CoreCmpPartialEqRow
  assert_fields_are_eq := Row.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [guide_check::next_kind]:
    Source: 'crates/guide-check/src/lib.rs', lines 294:0-311:1
    Visibility: public -/
def next_kind
  (removed : Slice Bool) (added : Slice Bool) (i : Std.Usize) (j : Std.Usize) :
  Result Kind
  := do
  let i1 := Slice.len removed
  if i < i1
  then
    let b ← Slice.index_usize removed i
    if b
    then ok Kind.Removed
    else
      let i2 := Slice.len added
      if j < i2
      then
        let b1 ← Slice.index_usize added j
        if b1
        then ok Kind.Added
        else
          let i3 := Slice.len removed
          if i < i3
          then
            let i4 := Slice.len added
            if j < i4
            then ok Kind.Same
            else ok Kind.Header
          else ok Kind.Header
      else
        let i3 := Slice.len removed
        if i < i3
        then
          let i4 := Slice.len added
          if j < i4
          then ok Kind.Same
          else ok Kind.Header
        else ok Kind.Header
  else
    let i2 := Slice.len added
    if j < i2
    then
      let b ← Slice.index_usize added j
      if b
      then ok Kind.Added
      else
        let i3 := Slice.len removed
        if i < i3
        then
          let i4 := Slice.len added
          if j < i4
          then ok Kind.Same
          else ok Kind.Header
        else ok Kind.Header
    else
      let i3 := Slice.len removed
      if i < i3
      then
        let i4 := Slice.len added
        if j < i4
        then ok Kind.Same
        else ok Kind.Header
      else ok Kind.Header

/-- [guide_check::number_rows]: loop body 0:
    Source: 'crates/guide-check/src/lib.rs', lines 320:4-342:1
    Visibility: public -/
@[rust_loop_body]
def number_rows_loop.body
  (removed : Slice Bool) (added : Slice Bool) (out : alloc.vec.Vec Row)
  (i : Std.Usize) (j : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Row) × Std.Usize × Std.Usize)
    (alloc.vec.Vec Row))
  := do
  let i1 := Slice.len removed
  let i2 := Slice.len added
  let b ← lines_left i i1 j i2
  if b
  then
    let kind ← next_kind removed added i j
    match kind with
    | Kind.Same =>
      let i3 ← i + 1#usize
      let j1 ← j + 1#usize
      let out1 ←
        alloc.vec.Vec.push out ({ kind := Kind.Same, old := i3, new := j1 } :
          Row)
      ok (cont (out1, i3, j1))
    | Kind.Removed =>
      let i3 ← i + 1#usize
      let out1 ←
        alloc.vec.Vec.push out
          ({ kind := Kind.Removed, old := i3, new := 0#usize } : Row)
      ok (cont (out1, i3, j))
    | Kind.Added =>
      let j1 ← j + 1#usize
      let out1 ←
        alloc.vec.Vec.push out
          ({ kind := Kind.Added, old := 0#usize, new := j1 } : Row)
      ok (cont (out1, i, j1))
    | Kind.Header => ok (done out)
  else ok (done out)

/-- [guide_check::number_rows]: loop 0:
    Source: 'crates/guide-check/src/lib.rs', lines 320:4-342:1
    Visibility: public -/
@[rust_loop]
def number_rows_loop
  (removed : Slice Bool) (added : Slice Bool) (out : alloc.vec.Vec Row)
  (i : Std.Usize) (j : Std.Usize) :
  Result (alloc.vec.Vec Row)
  := do
  loop
    (fun (out1, i1, j1) => number_rows_loop.body removed added out1 i1 j1)
    (out, i, j)

/-- [guide_check::number_rows]:
    Source: 'crates/guide-check/src/lib.rs', lines 316:0-342:1
    Visibility: public -/
@[reducible]
def number_rows
  (removed : Slice Bool) (added : Slice Bool) :
  Result (alloc.vec.Vec Row)
  := do
  number_rows_loop removed added (alloc.vec.Vec.new Row) 0#usize 0#usize

/-- [guide_check::is_change]:
    Source: 'crates/guide-check/src/lib.rs', lines 344:0-350:1
    Visibility: public -/
def is_change (r : Row) : Result Bool := do
  match r.kind with
  | Kind.Same => ok false
  | Kind.Removed => ok true
  | Kind.Added => ok true
  | Kind.Header => ok false

/-- [guide_check::window_start]:
    Source: 'crates/guide-check/src/lib.rs', lines 353:0-358:1
    Visibility: public -/
def window_start (k : Std.Usize) (ctx : Std.Usize) : Result Std.Usize := do
  if k > ctx
  then k - ctx
  else ok 0#usize

/-- [guide_check::window_end]:
    Source: 'crates/guide-check/src/lib.rs', lines 361:0-366:1
    Visibility: public -/
def window_end
  (k : Std.Usize) (ctx : Std.Usize) (len : Std.Usize) : Result Std.Usize := do
  let i ← len - k
  if ctx < i
  then let i1 ← k + ctx
       i1 + 1#usize
  else ok len

/-- [guide_check::near_change]: loop body 0:
    Source: 'crates/guide-check/src/lib.rs', lines 372:4-379:1
    Visibility: public -/
@[rust_loop_body]
def near_change_loop.body
  (rows : Slice Row) («end» : Std.Usize) (c : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  if c < «end»
  then
    let r ← Slice.index_usize rows c
    let b ← is_change r
    if b
    then ok (done true)
    else let c1 ← c + 1#usize
         ok (cont c1)
  else ok (done false)

/-- [guide_check::near_change]: loop 0:
    Source: 'crates/guide-check/src/lib.rs', lines 372:4-379:1
    Visibility: public -/
@[rust_loop]
def near_change_loop
  (rows : Slice Row) (c : Std.Usize) («end» : Std.Usize) : Result Bool := do
  loop
    (fun c1 => near_change_loop.body rows «end» c1)
    c

/-- [guide_check::near_change]:
    Source: 'crates/guide-check/src/lib.rs', lines 369:0-379:1
    Visibility: public -/
def near_change
  (rows : Slice Row) (k : Std.Usize) (ctx : Std.Usize) : Result Bool := do
  let c ← window_start k ctx
  let i := Slice.len rows
  let «end» ← window_end k ctx i
  near_change_loop rows c «end»

/-- [guide_check::shows_old]:
    Source: 'crates/guide-check/src/lib.rs', lines 382:0-388:1
    Visibility: public -/
def shows_old (r : Row) : Result Bool := do
  match r.kind with
  | Kind.Same => ok true
  | Kind.Removed => ok true
  | Kind.Added => ok false
  | Kind.Header => ok false

/-- [guide_check::shows_new]:
    Source: 'crates/guide-check/src/lib.rs', lines 391:0-397:1
    Visibility: public -/
def shows_new (r : Row) : Result Bool := do
  match r.kind with
  | Kind.Same => ok true
  | Kind.Removed => ok false
  | Kind.Added => ok true
  | Kind.Header => ok false

/-- [guide_check::bump]:
    Source: 'crates/guide-check/src/lib.rs', lines 400:0-405:1
    Visibility: public -/
def bump (n : Std.Usize) (b : Bool) : Result Std.Usize := do
  if b
  then n + 1#usize
  else ok n

/-- [guide_check::keep_row]:
    Source: 'crates/guide-check/src/lib.rs', lines 409:0-418:1
    Visibility: public -/
def keep_row
  (out : alloc.vec.Vec Row) (kept : Bool) (r : Row) (old : Std.Usize)
  (new : Std.Usize) :
  Result (alloc.vec.Vec Row)
  := do
  let out1 ←
    if kept
    then ok out
    else alloc.vec.Vec.push out ({ kind := Kind.Header, old, new } : Row)
  alloc.vec.Vec.push out1 r

/-- [guide_check::cut_rows]: loop body 0:
    Source: 'crates/guide-check/src/lib.rs', lines 431:4-440:5
    Visibility: public -/
@[rust_loop_body]
def cut_rows_loop.body
  (rows : Slice Row) (ctx : Std.Usize) (out : alloc.vec.Vec Row)
  (k : Std.Usize) (old : Std.Usize) (new : Std.Usize) (kept : Bool) :
  Result (ControlFlow ((alloc.vec.Vec Row) × Std.Usize × Std.Usize ×
    Std.Usize × Bool) (alloc.vec.Vec Row))
  := do
  let i := Slice.len rows
  if k < i
  then
    let near1 ← near_change rows k ctx
    let out1 ←
      if near1
      then do
           let r ← Slice.index_usize rows k
           keep_row out kept r old new
      else ok out
    let r ← Slice.index_usize rows k
    let b ← shows_old r
    let old1 ← bump old b
    let b1 ← shows_new r
    let new1 ← bump new b1
    let k1 ← k + 1#usize
    ok (cont (out1, k1, old1, new1, near1))
  else ok (done out)

/-- [guide_check::cut_rows]: loop 0:
    Source: 'crates/guide-check/src/lib.rs', lines 431:4-440:5
    Visibility: public -/
@[rust_loop]
def cut_rows_loop
  (rows : Slice Row) (ctx : Std.Usize) (out : alloc.vec.Vec Row)
  (k : Std.Usize) (old : Std.Usize) (new : Std.Usize) (kept : Bool) :
  Result (alloc.vec.Vec Row)
  := do
  loop
    (fun (out1, k1, old1, new1, kept1) => cut_rows_loop.body rows ctx out1 k1
      old1 new1 kept1)
    (out, k, old, new, kept)

/-- [guide_check::cut_rows]:
    Source: 'crates/guide-check/src/lib.rs', lines 424:0-442:1
    Visibility: public -/
@[reducible]
def cut_rows
  (rows : Slice Row) (ctx : Std.Usize) : Result (alloc.vec.Vec Row) := do
  cut_rows_loop rows ctx (alloc.vec.Vec.new Row) 0#usize 1#usize 1#usize false

end guide_check
