-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [guide_check]: function definitions
import Aeneas
import GuideCheck.Code.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace guide_check

/-- [guide_check::bytes_equal]: loop body 0:
    Source: 'crates/guide-check/src/lib.rs', lines 44:4-51:1
    Visibility: public -/
@[rust_loop_body]
def bytes_equal_loop.body
  (a : Slice Std.U8) (b : Slice Std.U8) (i : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i1 := Slice.len a
  if i < i1
  then
    let i2 ← Slice.index_usize a i
    let i3 ← Slice.index_usize b i
    if i2 != i3
    then ok (done false)
    else let i4 ← i + 1#usize
         ok (cont i4)
  else ok (done true)

/-- [guide_check::bytes_equal]: loop 0:
    Source: 'crates/guide-check/src/lib.rs', lines 44:4-51:1
    Visibility: public -/
@[rust_loop]
def bytes_equal_loop
  (a : Slice Std.U8) (b : Slice Std.U8) (i : Std.Usize) : Result Bool := do
  loop
    (fun i1 => bytes_equal_loop.body a b i1)
    i

/-- [guide_check::bytes_equal]:
    Source: 'crates/guide-check/src/lib.rs', lines 39:0-51:1
    Visibility: public -/
def bytes_equal (a : Slice Std.U8) (b : Slice Std.U8) : Result Bool := do
  let i := Slice.len a
  let i1 := Slice.len b
  if i != i1
  then ok false
  else bytes_equal_loop a b 0#usize

/-- [guide_check::next_kept]: loop body 0:
    Source: 'crates/guide-check/src/lib.rs', lines 56:4-63:1
    Visibility: public -/
@[rust_loop_body]
def next_kept_loop.body
  (mask : Slice Bool) (j : Std.Usize) :
  Result (ControlFlow Std.Usize Std.Usize)
  := do
  let i := Slice.len mask
  if j < i
  then
    let b ← Slice.index_usize mask j
    if b
    then let j1 ← j + 1#usize
         ok (cont j1)
    else ok (done j)
  else ok (done j)

/-- [guide_check::next_kept]: loop 0:
    Source: 'crates/guide-check/src/lib.rs', lines 56:4-63:1
    Visibility: public -/
@[rust_loop]
def next_kept_loop (mask : Slice Bool) (j : Std.Usize) : Result Std.Usize := do
  loop
    (fun j1 => next_kept_loop.body mask j1)
    j

/-- [guide_check::next_kept]:
    Source: 'crates/guide-check/src/lib.rs', lines 54:0-63:1
    Visibility: public -/
@[reducible]
def next_kept (mask : Slice Bool) (i : Std.Usize) : Result Std.Usize := do
  next_kept_loop mask i

/-- [guide_check::lines_left]:
    Source: 'crates/guide-check/src/lib.rs', lines 66:0-71:1
    Visibility: public -/
def lines_left
  (i : Std.Usize) (n : Std.Usize) (j : Std.Usize) (m : Std.Usize) :
  Result Bool
  := do
  if i < n
  then ok true
  else ok (j < m)

/-- [guide_check::kept_equal_from]: loop body 0:
    Source: 'crates/guide-check/src/lib.rs', lines 1:0-101:1
    Visibility: public -/
@[rust_loop_body]
def kept_equal_from_loop.body
  (old : Slice (alloc.vec.Vec Std.U8)) (removed : Slice Bool)
  (new : Slice (alloc.vec.Vec Std.U8)) (added : Slice Bool) (i : Std.Usize)
  (j : Std.Usize) :
  Result (ControlFlow (Std.Usize × Std.Usize) Bool)
  := do
  let i1 := Slice.len old
  let i2 := Slice.len new
  let b ← lines_left i i1 j i2
  if b
  then
    let a ← next_kept removed i
    let b1 ← next_kept added j
    let i3 := Slice.len old
    if a >= i3
    then let i4 := Slice.len new
         ok (done (b1 >= i4))
    else
      let i4 := Slice.len new
      if b1 >= i4
      then ok (done false)
      else
        let v ← Slice.index_usize old a
        let s := alloc.vec.Vec.deref v
        let v1 ← Slice.index_usize new b1
        let s1 := alloc.vec.Vec.deref v1
        let b2 ← bytes_equal s s1
        if b2
        then let i5 ← a + 1#usize
             let j1 ← b1 + 1#usize
             ok (cont (i5, j1))
        else ok (done false)
  else ok (done true)

/-- [guide_check::kept_equal_from]: loop 0:
    Source: 'crates/guide-check/src/lib.rs', lines 1:0-101:1
    Visibility: public -/
@[rust_loop]
def kept_equal_from_loop
  (old : Slice (alloc.vec.Vec Std.U8)) (removed : Slice Bool)
  (new : Slice (alloc.vec.Vec Std.U8)) (added : Slice Bool) (i : Std.Usize)
  (j : Std.Usize) :
  Result Bool
  := do
  loop
    (fun (i1, j1) => kept_equal_from_loop.body old removed new added i1 j1)
    (i, j)

/-- [guide_check::kept_equal_from]:
    Source: 'crates/guide-check/src/lib.rs', lines 75:0-101:1
    Visibility: public -/
@[reducible]
def kept_equal_from
  (old : Slice (alloc.vec.Vec Std.U8)) (removed : Slice Bool)
  (new : Slice (alloc.vec.Vec Std.U8)) (added : Slice Bool) (i0 : Std.Usize)
  (j0 : Std.Usize) :
  Result Bool
  := do
  kept_equal_from_loop old removed new added i0 j0

/-- [guide_check::span_holds]:
    Source: 'crates/guide-check/src/lib.rs', lines 104:0-115:1
    Visibility: public -/
def span_holds
  (s : Span) (file : Std.Usize) (old : Bool) (line : Std.Usize) :
  Result Bool
  := do
  if s.file != file
  then ok false
  else
    if s.old != old
    then ok false
    else if line < s.from
         then ok false
         else ok (line <= s.to)

/-- [guide_check::covered]: loop body 0:
    Source: 'crates/guide-check/src/lib.rs', lines 120:4-127:1
    Visibility: public -/
@[rust_loop_body]
def covered_loop.body
  (spans : Slice Span) (file : Std.Usize) (old : Bool) (line : Std.Usize)
  (i : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i1 := Slice.len spans
  if i < i1
  then
    let s ← Slice.index_usize spans i
    let b ← span_holds s file old line
    if b
    then ok (done true)
    else let i2 ← i + 1#usize
         ok (cont i2)
  else ok (done false)

/-- [guide_check::covered]: loop 0:
    Source: 'crates/guide-check/src/lib.rs', lines 120:4-127:1
    Visibility: public -/
@[rust_loop]
def covered_loop
  (spans : Slice Span) (file : Std.Usize) (old : Bool) (line : Std.Usize)
  (i : Std.Usize) :
  Result Bool
  := do
  loop
    (fun i1 => covered_loop.body spans file old line i1)
    i

/-- [guide_check::covered]:
    Source: 'crates/guide-check/src/lib.rs', lines 118:0-127:1
    Visibility: public -/
@[reducible]
def covered
  (spans : Slice Span) (file : Std.Usize) (old : Bool) (line : Std.Usize) :
  Result Bool
  := do
  covered_loop spans file old line 0#usize

/-- [guide_check::mask_covered]: loop body 0:
    Source: 'crates/guide-check/src/lib.rs', lines 132:4-141:1
    Visibility: public -/
@[rust_loop_body]
def mask_covered_loop.body
  (spans : Slice Span) (file : Std.Usize) (old : Bool) (mask : Slice Bool)
  (k : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i := Slice.len mask
  if k < i
  then
    let b ← Slice.index_usize mask k
    if b
    then
      let i1 ← k + 1#usize
      let b1 ← covered spans file old i1
      if b1
      then ok (cont i1)
      else ok (done false)
    else let k1 ← k + 1#usize
         ok (cont k1)
  else ok (done true)

/-- [guide_check::mask_covered]: loop 0:
    Source: 'crates/guide-check/src/lib.rs', lines 132:4-141:1
    Visibility: public -/
@[rust_loop]
def mask_covered_loop
  (spans : Slice Span) (file : Std.Usize) (old : Bool) (mask : Slice Bool)
  (k : Std.Usize) :
  Result Bool
  := do
  loop
    (fun k1 => mask_covered_loop.body spans file old mask k1)
    k

/-- [guide_check::mask_covered]:
    Source: 'crates/guide-check/src/lib.rs', lines 130:0-141:1
    Visibility: public -/
@[reducible]
def mask_covered
  (spans : Slice Span) (file : Std.Usize) (old : Bool) (mask : Slice Bool) :
  Result Bool
  := do
  mask_covered_loop spans file old mask 0#usize

/-- [guide_check::file_ok]:
    Source: 'crates/guide-check/src/lib.rs', lines 144:0-158:1
    Visibility: public -/
def file_ok
  (d : FileDiff) (f : Std.Usize) (spans : Slice Span) : Result Bool := do
  let i := alloc.vec.Vec.len d.removed
  let i1 := alloc.vec.Vec.len d.old
  if i != i1
  then ok false
  else
    let i2 := alloc.vec.Vec.len d.added
    let i3 := alloc.vec.Vec.len d.new
    if i2 != i3
    then ok false
    else
      let s := alloc.vec.Vec.deref d.old
      let s1 := alloc.vec.Vec.deref d.removed
      let s2 := alloc.vec.Vec.deref d.new
      let s3 := alloc.vec.Vec.deref d.added
      let b ← kept_equal_from s s1 s2 s3 0#usize 0#usize
      if b
      then
        let s4 := alloc.vec.Vec.deref d.removed
        let b1 ← mask_covered spans f true s4
        if b1
        then
          let s5 := alloc.vec.Vec.deref d.added
          mask_covered spans f false s5
        else ok false
      else ok false

/-- [guide_check::files_ok]: loop body 0:
    Source: 'crates/guide-check/src/lib.rs', lines 163:4-170:1
    Visibility: public -/
@[rust_loop_body]
def files_ok_loop.body
  (files : Slice FileDiff) (spans : Slice Span) (f : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i := Slice.len files
  if f < i
  then
    let fd ← Slice.index_usize files f
    let b ← file_ok fd f spans
    if b
    then let f1 ← f + 1#usize
         ok (cont f1)
    else ok (done false)
  else ok (done true)

/-- [guide_check::files_ok]: loop 0:
    Source: 'crates/guide-check/src/lib.rs', lines 163:4-170:1
    Visibility: public -/
@[rust_loop]
def files_ok_loop
  (files : Slice FileDiff) (spans : Slice Span) (f : Std.Usize) :
  Result Bool
  := do
  loop
    (fun f1 => files_ok_loop.body files spans f1)
    f

/-- [guide_check::files_ok]:
    Source: 'crates/guide-check/src/lib.rs', lines 161:0-170:1
    Visibility: public -/
@[reducible]
def files_ok (files : Slice FileDiff) (spans : Slice Span) : Result Bool := do
  files_ok_loop files spans 0#usize

/-- [guide_check::has_change]: loop body 0:
    Source: 'crates/guide-check/src/lib.rs', lines 176:4-183:1
    Visibility: public -/
@[rust_loop_body]
def has_change_loop.body
  (mask : Slice Bool) («to» : Std.Usize) (k : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  if k < «to»
  then
    let b ← Slice.index_usize mask k
    if b
    then ok (done true)
    else let k1 ← k + 1#usize
         ok (cont k1)
  else ok (done false)

/-- [guide_check::has_change]: loop 0:
    Source: 'crates/guide-check/src/lib.rs', lines 176:4-183:1
    Visibility: public -/
@[rust_loop]
def has_change_loop
  (mask : Slice Bool) («to» : Std.Usize) (k : Std.Usize) : Result Bool := do
  loop
    (fun k1 => has_change_loop.body mask «to» k1)
    k

/-- [guide_check::has_change]:
    Source: 'crates/guide-check/src/lib.rs', lines 174:0-183:1
    Visibility: public -/
def has_change
  (mask : Slice Bool) («from» : Std.Usize) («to» : Std.Usize) :
  Result Bool
  := do
  let k ← «from» - 1#usize
  has_change_loop mask «to» k

/-- [guide_check::dist]:
    Source: 'crates/guide-check/src/lib.rs', lines 185:0-190:1
    Visibility: public -/
def dist (a : Std.Usize) (b : Std.Usize) : Result Std.Usize := do
  if a < b
  then b - a
  else a - b

/-- [guide_check::near]: loop body 0:
    Source: 'crates/guide-check/src/lib.rs', lines 195:4-204:1
    Visibility: public -/
@[rust_loop_body]
def near_loop.body
  (mask : Slice Bool) (line : Std.Usize) (pad : Std.Usize) (k : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i := Slice.len mask
  if k < i
  then
    let b ← Slice.index_usize mask k
    if b
    then
      let i1 ← k + 1#usize
      let i2 ← dist i1 line
      if i2 <= pad
      then ok (done true)
      else ok (cont i1)
    else let k1 ← k + 1#usize
         ok (cont k1)
  else ok (done false)

/-- [guide_check::near]: loop 0:
    Source: 'crates/guide-check/src/lib.rs', lines 195:4-204:1
    Visibility: public -/
@[rust_loop]
def near_loop
  (mask : Slice Bool) (line : Std.Usize) (pad : Std.Usize) (k : Std.Usize) :
  Result Bool
  := do
  loop
    (fun k1 => near_loop.body mask line pad k1)
    k

/-- [guide_check::near]:
    Source: 'crates/guide-check/src/lib.rs', lines 193:0-204:1
    Visibility: public -/
@[reducible]
def near
  (mask : Slice Bool) (line : Std.Usize) (pad : Std.Usize) : Result Bool := do
  near_loop mask line pad 0#usize

/-- [guide_check::all_near]: loop body 0:
    Source: 'crates/guide-check/src/lib.rs', lines 209:4-216:1
    Visibility: public -/
@[rust_loop_body]
def all_near_loop.body
  (mask : Slice Bool) («to» : Std.Usize) (pad : Std.Usize) (k : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  if k < «to»
  then
    let i ← k + 1#usize
    let b ← near mask i pad
    if b
    then ok (cont i)
    else ok (done false)
  else ok (done true)

/-- [guide_check::all_near]: loop 0:
    Source: 'crates/guide-check/src/lib.rs', lines 209:4-216:1
    Visibility: public -/
@[rust_loop]
def all_near_loop
  (mask : Slice Bool) («to» : Std.Usize) (pad : Std.Usize) (k : Std.Usize) :
  Result Bool
  := do
  loop
    (fun k1 => all_near_loop.body mask «to» pad k1)
    k

/-- [guide_check::all_near]:
    Source: 'crates/guide-check/src/lib.rs', lines 207:0-216:1
    Visibility: public -/
def all_near
  (mask : Slice Bool) («from» : Std.Usize) («to» : Std.Usize)
  (pad : Std.Usize) :
  Result Bool
  := do
  let k ← «from» - 1#usize
  all_near_loop mask «to» pad k

/-- [guide_check::span_fits]:
    Source: 'crates/guide-check/src/lib.rs', lines 219:0-233:1
    Visibility: public -/
def span_fits
  (mask : Slice Bool) («from» : Std.Usize) («to» : Std.Usize)
  (pad : Std.Usize) :
  Result Bool
  := do
  if «from» = 0#usize
  then ok false
  else
    if «from» > «to»
    then ok false
    else
      let i := Slice.len mask
      if «to» > i
      then ok false
      else
        let b ← has_change mask «from» «to»
        if b
        then all_near mask «from» «to» pad
        else ok false

/-- [guide_check::span_ok]:
    Source: 'crates/guide-check/src/lib.rs', lines 235:0-243:1
    Visibility: public -/
def span_ok
  (s : Span) (files : Slice FileDiff) (pad : Std.Usize) : Result Bool := do
  let i := Slice.len files
  if s.file >= i
  then ok false
  else
    if s.old
    then
      let fd ← Slice.index_usize files s.file
      let s1 := alloc.vec.Vec.deref fd.removed
      span_fits s1 s.from s.to pad
    else
      let fd ← Slice.index_usize files s.file
      let s1 := alloc.vec.Vec.deref fd.added
      span_fits s1 s.from s.to pad

/-- [guide_check::spans_ok]: loop body 0:
    Source: 'crates/guide-check/src/lib.rs', lines 247:4-254:1
    Visibility: public -/
@[rust_loop_body]
def spans_ok_loop.body
  (spans : Slice Span) (files : Slice FileDiff) (pad : Std.Usize)
  (i : Std.Usize) :
  Result (ControlFlow Std.Usize Bool)
  := do
  let i1 := Slice.len spans
  if i < i1
  then
    let s ← Slice.index_usize spans i
    let b ← span_ok s files pad
    if b
    then let i2 ← i + 1#usize
         ok (cont i2)
    else ok (done false)
  else ok (done true)

/-- [guide_check::spans_ok]: loop 0:
    Source: 'crates/guide-check/src/lib.rs', lines 247:4-254:1
    Visibility: public -/
@[rust_loop]
def spans_ok_loop
  (spans : Slice Span) (files : Slice FileDiff) (pad : Std.Usize)
  (i : Std.Usize) :
  Result Bool
  := do
  loop
    (fun i1 => spans_ok_loop.body spans files pad i1)
    i

/-- [guide_check::spans_ok]:
    Source: 'crates/guide-check/src/lib.rs', lines 245:0-254:1
    Visibility: public -/
@[reducible]
def spans_ok
  (spans : Slice Span) (files : Slice FileDiff) (pad : Std.Usize) :
  Result Bool
  := do
  spans_ok_loop spans files pad 0#usize

/-- [guide_check::check]:
    Source: 'crates/guide-check/src/lib.rs', lines 257:0-262:1
    Visibility: public -/
def check
  (files : Slice FileDiff) (spans : Slice Span) (pad : Std.Usize) :
  Result Bool
  := do
  let b ← files_ok files spans
  if b
  then spans_ok spans files pad
  else ok false

end guide_check
