-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [guide_check]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace guide_check

/-- [guide_check::FileDiff]
    Source: 'crates/guide-check/src/lib.rs', lines 23:0-28:1
    Visibility: public -/
structure FileDiff where
  old : alloc.vec.Vec (alloc.vec.Vec Std.U8)
  new : alloc.vec.Vec (alloc.vec.Vec Std.U8)
  removed : alloc.vec.Vec Bool
  added : alloc.vec.Vec Bool

/-- [guide_check::Span]
    Source: 'crates/guide-check/src/lib.rs', lines 32:0-37:1
    Visibility: public -/
structure Span where
  file : Std.Usize
  old : Bool
  «from» : Std.Usize
  «to» : Std.Usize

end guide_check
